version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/prod/php/Dockerfile.prod
    container_name: php-fpm-prod
    expose:
      - "9000"  # Nginx からアクセスするため
    networks:
      - app-network
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: docker/prod/node/Dockerfile.prod
    container_name: nuxt-app-prod
    expose:
      - "3000"  # Nginx からアクセス
    networks:
      - app-network

  nginx:
    build:
      dockerfile: docker/prod/nginx/Dockerfile.prod
    container_name: nginx-prod
    ports:
      - "80:80"
    depends_on:
      - php
      - node
    networks:
      - app-network

  db:
    platform: linux/amd64
    image: mysql:5.7.36
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diary-app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - db_my.cnf:/etc/mysql/conf.d/my.cnf
      - db_sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  db_data:
  db_my.cnf:
  db_sql:

networks:
  app-network:
    driver: bridge
